export const BASE_URL='https://chaloghoomneapi.kickrtechnology.in/api/v1/'
// export const REACT_URL = 'https://adminchaloghoomne.kickrtech.in'
export const REACT_URL ='http://localhost:5174'

// export const BASE_URL = "https://api.chaloghoomne.com/api/v1/";

export const NetworkConfig = {
  ADDCONTENT: "/add-content",
  ADMINLOGIN: "admin-login",
  FORGOTPASSWORD: "admin-forgot-password",
  FORGOTPASSWORDVERIFYOTP: "admin-forgot-password",
  RESETADMINPASSWORD: "admin-change-password",
  ACCEPTEDUSERS: "approved-profiles",
  USERSTATUS: "process-profile",
  REJECTEDUSERS: "rejected-profiles",
  PENDINGUSERS: "pending-profiles",
  BLOCKEDUSERS: "blocked-users",
  ADDEVENT: "add-event",
  USERBYID: "user",
  SUSPENDEDUSER: "suspend-user",
  DELETECONTENT: "delete-content",
  UPDATECONTENT: "update-content",
  GETUSERS: "users",
  SEND_NOTIFICATION: "notify-all",
  GET_HEADING_BY_ID: "page-type",
  APPROVED_POSTS: "approved-post",
  REJECTED_POSTS: "rejected-post",
  PROCESS_POST: "process-post",
  GET_PROFILE_PIC: "admin-profile",
  UPDATE_PROFILE_PIC: "admin-edit-profile",
  CHANGE_PASSWORD: "admin-change-password",
  ADDPLAN: "add-plan",
  EDITPLAN: "edit-plan",
  NOTIFICATIONLST: "admin-notifications",
  NOTIFICATIONUSERSLST: "users-notifications",
  DASHBOARD: "dashboard",
  DELETEUSER: "delete-user",
  GET_CHAPTERS: "chapter",
  GET_SECTORS: "sectors-admin",
  GET_SERVICES: "services-admin",
  EDIT_CHAPTER: "chapter",
  EDIT_SECTOR: "edit-sector",
  GET_CHAPTER_SECTOR_BY_ID: "chapter-sector-by-id",
  ADD_SECTOR: "add-sector",
  ADD_ISSUE: "add-issue",
  GET_ISSUES: "issues",
  GET_TICKETS: "tickets",
  MADEREQUEST: "/requested-companies",
  REQUESTRECEIVED: "requester-companies",
  BLOCKUSER: "block-user",
  DELETE_SECTOR: "delete-sector",
  DELETE_SERVICE: "delete-service",
  FEATURED_SERVICE: "feature-service",
  GET_CITIES: "city-for-dropdown",
  TRANSFERUSER: "change-user-chapter-bulk",
  FEATURED_EVENT: "feature-event",
  FEATURED_SECTOR: "feature-sector",
  DELETE_CHAPTER: "delete-chapter",
  GET_CATEGORIES: "support-cat",
  ADD_SUBCATEGORY: "support-sub-cat",
  ADD_CATEGORY: "support-cat",
  GET_SUBCATEGORIES: "get-sub-categories",
  GET_SUBCATEGORY_BY_ID: "get-sub-category",
  GET_CATEGORY_BY_ID: "get-support-category",
  EDIT_SUBCATEGORY: "edit-sub-cat",
  EDIT_CATEGORY: "edit-support-cat",
  DELETE_CATEGORY: "delete-support-cat",
  DELETE_SUBCATEGORY: "delete-sub-cat",
  ADD_SPONSORSPEAKER: "add-sponsor",
  GET_EMPLOYEE: "employee",
  ADD_EMPLOYEE: "employee",
  GET_SPONSORS: "sponsors",
  GET_SPEAKERS: "sponsors",
  EMPLOYEE_LIST: "employee",
  EVENT_LIST: "get-events",
  EVENT_LIST_DELETE: "event",
  EMPLOYEE_LIST_DELETE: "employee",
  EDITEVENT: "event",
  EDITEMPLOYEE: "employee",
  APKFILE: "apk",
  ADD_TICKET: "event-ticket",
};
